### ISSUE TITLE
Build problem after 'npm audit fix'

### ISSUE THREAD

**Issue by Hatead1** [retejs/connection-plugin#15]
Error:
(node:5580) UnhandledPromiseRejectionWarning: Error: Line 9: Unexpected token :
    at ErrorHandler.constructError (C:\project-last\connection-plugin\node_modules\esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (C:\project-last\connection-plugin\node_modules\esprima\dist\esprima.js:5028:27)
    at Parser.unexpectedTokenError (C:\project-last\connection-plugin\node_modules\esprima\dist\esprima.js:1985:39)
    at Parser.throwUnexpectedToken (C:\project-last\connection-plugin\node_modules\esprima\dist\esprima.js:1995:21)
    at Parser.expect (C:\project-last\connection-plugin\node_modules\esprima\dist\esprima.js:2168:19)
    at Parser.parseFormalParameters (C:\project-last\connection-plugin\node_modules\esprima\dist\esprima.js:4274:23)
    at Parser.parseFunctionDeclaration (C:\project-last\connection-plugin\node_modules\esprima\dist\esprima.js:4337:38)
    at Parser.parseStatementListItem (C:\project-last\connection-plugin\node_modules\esprima\dist\esprima.js:3379:39)
    at Parser.parseScript (C:\project-last\connection-plugin\node_modules\esprima\dist\esprima.js:4723:29)
    at Object.parse (C:\project-last\connection-plugin\node_modules\esprima\dist\esprima.js:122:61)
(node:5580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Ni55aN** [comment]
After `npm audit fix` the rete-cli is updated to 0.6.0-rc.5, so the error occurs due to the lack of `@babel/preset-typescript` that was removed from the CLI and must be specified explicitly in the config in `babelPresets`

I'll upgrade it

**Comment by Hatead1** [comment]
Ok

**Comment by Ni55aN** [comment]
[v0.7.1](https://www.npmjs.com/package/rete-connection-plugin/v/0.7.1)
